#服务器配置信息
server:
  port: 8040
  servlet:
    context-path: /
#应用名称配置
spring:
  application:
    name: ms-gateway-zuul
#网关路由配置
zuul:
  ignoredServices: '*'
  routes:
    touch:
      path: /touch/**
      url: http://120.52.96.37:9091
      stripPrefix: false
      sensitiveHeaders:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
#logback日志配置
logging:
  path: ./log
  level:
    root: info
#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@120.52.96.37:8761/eureka/eureka
  instance:
    prefer-ip-address: true
    home-page-url-path: ${server.servlet.context-path}
management:
  server:
    servlet:
      context-path: ${server.servlet.context-path}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#服务Client配置
ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000